<!DOCTYPE html> <!-- This file was generated by the script: -->

<html dir="ltr" lang="sr"> <!-- Ovaj HTML dokument je generisan od strane skripte -->
    <head> <!-- Head section contains metadata and links to resources -->
        <meta charset="utf-8"/> <!-- Specifies the character enco$g for the HTML document, ensuring proper display of Serbian characters -->
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/> <!-- Sets the viewport for responsive design, making the page look good on mobile devices -->
        <!-- This meta tag ensures the page scales correctly on different devices -->
        <meta content="Bane (NoOneNeo) Paunović" name="author"/> <!-- Metadata declaring the author of the page -->
        <!-- This meta tag specifies the author of the page, useful for SEO and attribution -->
        <meta content="Web Development, PHP, Itruduction"  name="keywords"/> <!-- Metadata for keywords, used by search engines for indexing -->
        <meta content="Web Development, Learning PHP" name="description"/> <!-- Metadata for the page description, used by search engines and social media -->
        <meta content="index, follow" name="robots"/> <!-- Instructs search engine robots to index the page and follow its links -->
        <!-- This meta tag tells search engines to index the page and follow links -->
        <title>Learning PHP Introduction</title> <!-- Sets the title of the webpage, shown in the browser tab and search results -->
        <!-- This title appears in the browser tab and search engine results -->
        <link href="/phpmysql/uvod/assets/css/main.css" rel="stylesheet"/> <!-- Links to the external CSS file for page styling -->
        <!-- This link connects the HTML document to the CSS file for styling -->
        <script defer="" src="/phpmysql/uvod/assets/js/main.js"></script>  <!-- Loads the JavaScript file after HTML is parsed; "defer" ensures it runs after DOM is ready -->
        <!-- This script tag loads the JavaScript file, ensuring it runs after the HTML is fully parsed -->
            <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">   Links to the Bootstrap CSS file -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>  Loads the Bootstrap JavaScript bundle, which includes Popper.js for tooltips and popovers -->
            <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">     Links to the Flatpickr CSS file for date and time picker -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>  Loads the Flatpickr JavaScript library for date and time picking functionality -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js" defer></script>  Loads the Pikaday JavaScript library for date picking functionality -->
            <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css"> Links to the Pikaday CSS file for styling the date picker -->
            <!-- <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">  Links to the jQuery UI CSS file for additional UI components and styles -->
            <!-- <script src="https://code.jquery.com/jquery-3.7.1.min.js" defer></script>  Loads the jQuery library, which is a dependency for many JavaScript libraries and plugins -->
            <!-- <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" defer></script> Loads the jQuery UI library, which provides additional UI components and interactions -->
        <link href="/phpmysql/uvod/assets/pic/Logo.png" rel="icon" type="image/x-icon"/> <!-- Sets the favicon icon shown in browser tabs -->
        <link href="/phpmysql/uvod/assets/pic/logo.png" rel="apple-touch-icon"/> <!-- Defines an icon for Apple devices when saving the page to the home screen -->
    </head> <!-- Body section contains the content of the webpage -->
    <!-- This is the main content area of the webpage -->
        <body> <!-- Start of body section -->
    
        <FONT></FONT>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">

        </head>


        <?php        
          



            echo "Zdravo Branislave Paunoviću, ako ne naučiš PHP, nećeš moći da radiš na WordPressu!<br><hr>"; // ispisuje pozdravnu poruku sa HTML <br> i <hr> tagovima
            print_r("Zdravo Branislave Paunoviću, ako ne naučiš PHP, nećeš moći da radiš na WordPressu!<br><hr>"); // štampa niz u čitljivom formatu, ovde identično echo

            $bilosta1 = 5;  // deklariše promenljivu $bilosta1 i dodeljuje joj vrednost 5
            echo "<strong>" . "broj_1 : "  . "</strong>" . $bilosta1 ."<br><hr>"; // prikazuje podebljani label i vrednost $bilosta1 sa HTML formatiranjem

            $bilosta2 = 120; // deklariše promenljivu $bilosta2 i dodeljuje joj vrednost 120
            echo "<strong>" . "broj_2 : " . "</strong>" . $bilosta2 ."<br><hr>"; // prikazuje podebljani label i vrednost $bilosta2 sa HTML formatiranjem

            // ovaj kod služi da izračuna razliku dva broja
            $razlika = $bilosta1 - $bilosta2; // oduzima $bilosta2 od $bilosta1 i rezultat smešta u $razlika
            // ovaj kod služi da izračuna zbir dva broja
            $zbir =  $bilosta1 + $bilosta2; // sabira $bilosta1 i $bilosta2 i rezultat smešta u $zbir
            echo  "<div style='background: red; font-size: 24px;'> zbir broja $bilosta1 i broja $bilosta2 je </div>"  . $zbir; // ispisuje obojen div sa tekstom i sabranim rezultatom
            echo "<br><hr>"; // dodaje HTML <br> i <hr>

            /* komentar 
            može da se piše i 
            ovako */ // primer blok-komentara

            $rezultat = $bilosta1 % $bilosta2; // računa ostatak pri deljenju $bilosta1 sa $bilosta2 i smešta u $rezultat
            echo "<strong>" . "rezultat modula broja_1 i broja_2 = "  . "</strong>"  . $rezultat; // prikazuje label i izračunati modul
            echo "<br><hr>"; // dodaje HTML <br> i <hr>

            $deljenje = $bilosta2 / $bilosta1; // deli $bilosta2 sa $bilosta1 i rezultat smešta u $deljenje
            echo "<strong>" . "rezultat deljenja $bilosta2 sa $bilosta1 =  <span style=font-size:24px;>$deljenje </span>"  . "</strong>"; // prikazuje label i rezultat deljenja u uvećanom fontu
            echo "<br><hr>"; // dodaje HTML <br> i <hr>

            $text1 = "Zdravo"; // deklariše string promenljivu $text1
            $text2 = "Bane"; // deklariše string promenljivu $text2
            echo $text1 . " " . $text2; // konkatenira $text1, razmak i $text2 pa ispisuje
            echo "<br><hr>"; // dodaje HTML <br> i <hr>

            $BILOsta1 = 12; // deklariše promenljivu $BILOsta1 (velika slova) i dodeljuje joj 12
            echo $BILOsta1 ."<br><hr>"; // ispisuje vrednost i dodaje HTML <br> i <hr>

            $test = "Cao"; // deklariše string promenljivu $test
            echo $test; // ispisuje vrednost promenljive $test
            echo "<br><hr>"; // dodaje HTML <br> i <hr>
            
            echo "$bilosta1 minus $bilosta2, jednako je: <h1>$razlika</h1>"; // interpolacijom ubacuje promenljive u string i ispisuje razliku u <h1> tagu
            echo "<br><hr>"; // dodaje HTML <br> i <hr>

            echo "<h1><div style = 'background: green'> Ja cu postati programer </div> </h1>"; // prikazuje unutar <h1> tag zeleno obojen div sa tekstom

            $celi_broj = 11; // deklariše integer promenljivu $celi_broj
            $float_broj = 5.14; // deklariše float promenljivu $float_broj
            $prazno = null; // deklariše promenljivu $prazno bez vrednosti (null)
            $tacno = true; // deklariše boolean promenljivu $tacno sa vrednošću true
            $netacno = false; // deklariše boolean promenljivu $netacno sa vrednošću false

            var_dump($bilosta1); // ispisuje tip i vrednost promenljive $bilosta1
            echo "<br><hr>"; // dodaje HTML <br> i <hr>
            
            var_dump($bilosta2); // ispisuje tip i vrednost promenljive $bilosta2
            echo "<br><hr>"; // dodaje HTML <br> i <hr>
            
            var_dump($zbir); // ispisuje tip i vrednost promenljive $zbir
            echo "<br><hr>"; // dodaje HTML <br> i <hr>
            
            var_dump($test); // ispisuje tip i vrednost promenljive $test
            echo "<br><hr>"; // dodaje HTML <br> i <hr>
            
            var_dump($celi_broj); // ispisuje tip i vrednost promenljive $celi_broj
            echo "<br><hr>"; // dodaje HTML <br> i <hr>
            
            var_dump($float_broj); // ispisuje tip i vrednost promenljive $float_broj
            echo "<br><hr>"; // dodaje HTML <br> i <hr>
            
            var_dump($tacno); // ispisuje tip i vrednost promenljive $tacno
            echo "<br><hr>"; // dodaje HTML <br> i <hr>
            
            var_dump($netacno); // ispisuje tip i vrednost promenljive $netacno
            echo "<br><hr>"; // dodaje HTML <br> i <hr>
            
            var_dump($prazno); // ispisuje tip i vrednost promenljive $prazno (NULL)
            echo "<br><hr>"; // dodaje HTML <br> i <hr>
        ?>
    </body>
</html>