<!DOCTYPE html> <!-- This file was generated by the script: -->

<html dir="ltr" lang="sr"> <!-- Ovaj HTML dokument je generisan od strane skripte -->
    <head> <!-- Head section contains metadata and links to resources -->
        <meta charset="utf-8"/> <!-- Specifies the character enco$g for the HTML document, ensuring proper display of Serbian characters -->
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/> <!-- Sets the viewport for responsive design, making the page look good on mobile devices -->
        <!-- This meta tag ensures the page scales correctly on different devices -->
        <meta content="Bane (NoOneNeo) Paunović" name="author"/> <!-- Metadata declaring the author of the page -->
        <!-- This meta tag specifies the author of the page, useful for SEO and attribution -->
        <meta content="Web Development, PHP, Array"  name="keywords"/> <!-- Metadata for keywords, used by search engines for indexing -->
        <meta content="Web Development, Learning PHP Array" name="description"/> <!-- Metadata for the page description, used by search engines and social media -->
        <meta content="index, follow" name="robots"/> <!-- Instructs search engine robots to index the page and follow its links -->
        <!-- This meta tag tells search engines to index the page and follow links -->
        <title>Learning PHP Array</title> <!-- Sets the title of the webpage, shown in the browser tab and search results -->
        <!-- This title appears in the browser tab and search engine results -->
        <link href="/phpmysql/uvod/assets/css/main.css" rel="stylesheet"/> <!-- Links to the external CSS file for page styling -->
        <!-- This link connects the HTML document to the CSS file for styling -->
        <script defer="" src="/phpmysql/uvod/assets/js/main.js"></script>  <!-- Loads the JavaScript file after HTML is parsed; "defer" ensures it runs after DOM is ready -->
        <!-- This script tag loads the JavaScript file, ensuring it runs after the HTML is fully parsed -->
            <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">   Links to the Bootstrap CSS file -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>  Loads the Bootstrap JavaScript bundle, which includes Popper.js for tooltips and popovers -->
            <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">     Links to the Flatpickr CSS file for date and time picker -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>  Loads the Flatpickr JavaScript library for date and time picking functionality -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js" defer></script>  Loads the Pikaday JavaScript library for date picking functionality -->
            <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css"> Links to the Pikaday CSS file for styling the date picker -->
            <!-- <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">  Links to the jQuery UI CSS file for additional UI components and styles -->
            <!-- <script src="https://code.jquery.com/jquery-3.7.1.min.js" defer></script>  Loads the jQuery library, which is a dependency for many JavaScript libraries and plugins -->
            <!-- <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" defer></script> Loads the jQuery UI library, which provides additional UI components and interactions -->
        <link href="/phpmysql/uvod/assets/pic/Logo.png" rel="icon" type="image/x-icon"/> <!-- Sets the favicon icon shown in browser tabs -->
        <link href="/phpmysql/uvod/assets/pic/logo.png" rel="apple-touch-icon"/> <!-- Defines an icon for Apple devices when saving the page to the home screen -->
    </head> <!-- Body section contains the content of the webpage -->
    <!-- This is the main content area of the webpage -->
        <body> <!-- Start of body section -->
            <?php
            
                $niz = [10, 20, 50, 70, 90];                             // kreira indeksirani niz sa 5 elemenata
                var_dump($niz[3]);                                       // debug: ispiši detalje elementa na indeksu 3 (int(70))
                echo($niz[3]) . "<br><hr>";                              // ispiši vrednost elementa na indeksu 3 (70) - napomena: concat ovde ne radi kako misliš
                                                                        // (var_dump echo concat problem—bolje echo u zasebnom redu)

                $osoba = [                                              // kreira asocijativni niz (array) sa ključevima Ime, godine, zanimanje
                    "Ime"       => "Marko",
                    "godine"    => 18,
                    "zanimanje" => "programer"
                ]; // asocijativni niz

                var_dump($osoba);                                       // debug: ispiši celu strukturu asocijativnog niza
                echo "<br><hr>";                                        // HTML: novi red i horizontalna linija
                echo $osoba["Ime"] . "<br><hr>";                        // ispiši vrednost ključa "Ime" (Marko) i linija

                $gradovi = [                                            // višedimenzionalni (associative => indexed arrays)
                    "Srbija" => ["Beograd", "Novi Sad", "Niš"],
                    "Hrvatska" => ["Zagreb", "Rijeka", "Split"],
                    "Crna Gora" => ["Podgorica", "Nikšić", "Herceg Novi"],
                    "BiH" => ["Sarajevo", "Banja Luka", "Trebinje"]
                ]; // visedimenzionalni nizovi

                var_dump($gradovi);                                     // debug: ispiši kompletnu strukturu višedimenzionalnog niza

                $indeksi = [0, 2];                                      // niz indeksa koje želimo izabrati (0 = prvi, 2 = treći)
                $drzava = 'Crna Gora';                                  // promenljiva koja sadrži ime države koju indeksiramo

                foreach ($indeksi as $i) {                              // prolazak kroz svaki indeks (0 i 2)
                     // BEZBEDNO: prvo proverimo da li država postoji, pa da li indeks postoji
                    if (isset ($gradovi[$drzava][$i]))                  // PROVERA: da li postoji element na tom mestu (bezbedno čitanje)
                        echo "<br><hr>";                                // ako postoji, ispiši <br><hr>  (samo OVA linija zavisi od if zbog nedostatka {} )
                    echo "<strong>" . $gradovi[$drzava][$i] . "</strong><br><hr>"; // OVA linija se izvršava uvek; može izazvati NOTICE ako element ne postoji
                };                                                       // kraj foreach petlje

                $brojevi = [2, 4, 5 ];                                  // novi indeksirani niz sa 3 elementa
                var_dump($brojevi);                                     // debug: ispiši strukturu niza
                echo  "<br><hr>";                                       // HTML: novi red i linija
                $broj_elemenata_u_nizu = count($brojevi);               // prebrojava elemente niza (count -> 3)
                echo $broj_elemenata_u_nizu  . "<br><hr>";              // ispis broja elemenata (3) i linija

                array_push($brojevi, 10, 15);                           // dodaje elemente 10 i 15 na kraj niza
                var_dump($brojevi);                                     // debug: ispis niza posle dodavanja (sada 5 elemenata)
                echo  "<br><hr>";                                       // HTML: novi red i linija
                $broj_elemenata_u_nizu = count($brojevi);               // ponovo prebroj: sada vraća 5
                echo $broj_elemenata_u_nizu  . "<br><hr>";              // ispis novog broja elemenata (5) i linija

                $poslednji_element = array_pop($brojevi);               // uklanja i vraća poslednji element niza (15)
                echo $poslednji_element . "<br><hr>";                   // ispis poslednjeg elementa koji je uklonjen (15)
                var_dump($brojevi); echo "<br><hr>";                                     // debug: ispis niza nakon array_pop (sada [2,4,5,10])

                $brojevi_1 = [1 , 2, 3];
                $brojevi_2 = [4, 5, 6 ];

                $spojeni_nizovi = array_merge($brojevi_1, $brojevi_2);
                var_dump($spojeni_nizovi);  echo "<br><hr>";

                $sortiranje_brojeva = [5, 2, 1 ,4, 3];
                sort($sortiranje_brojeva);
                var_dump($sortiranje_brojeva); echo "<br><hr>";
                rsort($sortiranje_brojeva);
                var_dump($sortiranje_brojeva); echo "<br><hr>";
            ?>   
        </body>
</html>