<!DOCTYPE html> <!-- This file was generated by the script: -->

<html dir="ltr" lang="sr"> <!-- Ovaj HTML dokument je generisan od strane skripte -->
    <head> <!-- Head section contains metadata and links to resources -->
        <meta charset="utf-8"/> <!-- Specifies the character enco$g for the HTML document, ensuring proper display of Serbian characters -->
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/> <!-- Sets the viewport for responsive design, making the page look good on mobile devices -->
        <!-- This meta tag ensures the page scales correctly on different devices -->
        <meta content="Bane (NoOneNeo) Paunović" name="author"/> <!-- Metadata declaring the author of the page -->
        <!-- This meta tag specifies the author of the page, useful for SEO and attribution -->
        <meta content="Web Development, PHP, Conditions"  name="keywords"/> <!-- Metadata for keywords, used by search engines for indexing -->
        <meta content="Web Development, Learning PHP Conditions" name="description"/> <!-- Metadata for the page description, used by search engines and social media -->
        <meta content="index, follow" name="robots"/> <!-- Instructs search engine robots to index the page and follow its links -->
        <!-- This meta tag tells search engines to index the page and follow links -->
        <title>Learning PHP Conditions</title> <!-- Sets the title of the webpage, shown in the browser tab and search results -->
        <!-- This title appears in the browser tab and search engine results -->
        <link href="/phpmysql/uvod/assets/css/main.css" rel="stylesheet"/> <!-- Links to the external CSS file for page styling -->
        <!-- This link connects the HTML document to the CSS file for styling -->
        <script defer="" src="/phpmysql/uvod/assets/js/main.js"></script>  <!-- Loads the JavaScript file after HTML is parsed; "defer" ensures it runs after DOM is ready -->
        <!-- This script tag loads the JavaScript file, ensuring it runs after the HTML is fully parsed -->
            <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">   Links to the Bootstrap CSS file -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>  Loads the Bootstrap JavaScript bundle, which includes Popper.js for tooltips and popovers -->
            <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">     Links to the Flatpickr CSS file for date and time picker -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>  Loads the Flatpickr JavaScript library for date and time picking functionality -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js" defer></script>  Loads the Pikaday JavaScript library for date picking functionality -->
            <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css"> Links to the Pikaday CSS file for styling the date picker -->
            <!-- <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">  Links to the jQuery UI CSS file for additional UI components and styles -->
            <!-- <script src="https://code.jquery.com/jquery-3.7.1.min.js" defer></script>  Loads the jQuery library, which is a dependency for many JavaScript libraries and plugins -->
            <!-- <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" defer></script> Loads the jQuery UI library, which provides additional UI components and interactions -->
        <link href="/phpmysql/uvod/assets/pic/Logo.png" rel="icon" type="image/x-icon"/> <!-- Sets the favicon icon shown in browser tabs -->
        <link href="/phpmysql/uvod/assets/pic/logo.png" rel="apple-touch-icon"/> <!-- Defines an icon for Apple devices when saving the page to the home screen -->
    </head> <!-- Body section contains the content of the webpage -->
    <!-- This is the main content area of the webpage -->
        <body> <!-- Start of body section -->
                
        <?php
        // Vezbamo uslove

        $i = 0; // inicijalizujemo promenljivu $i na 0
        $broj = 3; // postavljamo promenljivu $broj na 3

        for ($i; $i < 5; $i++) { // pokrećemo petlju dok je $i manje od 5, nakon svake iteracije $i++
            if ($i == $broj ){ // proveravamo da li je $i jednako $broj
                echo "<h1>Broj je jednak $broj" . "<br> <hr></h1>"; // ispisujemo naslov da je broj jednak i liniju razdvajanja
                break; // prekidamo petlju jer smo našli jednako stanje
            }
            elseif ($i != $broj) { // ako $i nije jednako $broj
                if ($i < $broj){ // i ako je $i manje od $broj
                    echo " <h3>Broj je manji od $broj.</h3> " . "Trenutni broj je : $i" . "<br> <hr>"; // ispisujemo da je broj manji i prikazujemo $i
                }
                else { // u suprotnom je $i veće od $broj
                    echo " <h3>Broj je veci od $broj.</h3> " . "Trenutni broj je : $i" . "<br> <hr>"; // ispisujemo da je broj veći i prikazujemo $i
                }
            }   
        }

        $broj = 3; // (ponovo) postavljamo promenljivu $broj na 3

        for ($e = 0; $e < 5; $e++){ // nova petlja sa promenljivom $e od 0 do 4

            echo match (true) { // koristimo match izraz za uslove bazirane na boolean vrednosti
                $e === $broj => "<h1>Broj je jednak $broj</h1><hr>", // ako je stroga jednakost, ispisujemo poruku
                $e < $broj    => "<h3>Broj je manji od $broj.</h3> Trenutni broj je: $e<br><hr>", // ako je manje, ispisujemo tu poruku
                default       => "<h3>Broj je veći od $broj.</h3> Trenutni broj je: $e<br><hr>", // inače (veće ili bilo šta drugo), ispisujemo poruku o većem broju
            };
            // if ($e === $broj) break; // alternativa za prekidanje petlje, ali je zakomentarisano
        }

        echo "<div style='background:lightgrey; width:100%; height:50px;'></div>"; // ispisujemo sivu traku
        echo "<br> <hr>"; // umetamo prelom linije i horizontalu

        $donja_granica = 20; // definisana donja granica za unos
        $gornja_granica = 40; // definisana gornja granica za unos

        $raw  = filter_input(INPUT_GET, 'uneta_vrednost', FILTER_VALIDATE_INT); // učitavamo GET parametar i validiramo kao integer
        $broj = ($raw === null || $raw === false) ? null : $raw; // ako je validacija neuspešna ili ništa nije poslato, postavljamo $broj na null

        ?>

        <form method="get"> <!-- otvaramo formu koja šalje GET zahtev -->
        <label>Unesi broj:
            <input
            type="number"                   
            name="uneta_vrednost"           
            min="<?= $donja_granica ?>"      
            max="<?= $gornja_granica ?>"     
            step="1"                         
            value="<?= htmlspecialchars($broj ?? '') ?>" 
            > <!--brojčano polje za unos, ime podatka u GET nizu, minimalna vrednost za unos, maksimalna vrednost za unos, korak za inkrement, štitimo i vraćamo prethodni unos ako postoji -->
        </label>
        <button type="submit">Proveri</button> <!-- dugme za slanje forme -->
        </form>

        <?php
        if ($broj > $donja_granica && $broj < $gornja_granica){ // proveravamo da li je uneti broj između granica (isključivo)
            echo "Broj je izmedju $donja_granica i $gornja_granica"; // ispisujemo poruku ako jeste
        } else {
            echo "Broj je NIJE izmedju $donja_granica i $gornja_granica"; // ispisujemo poruku ako nije
        }
        ?>

    </body>
</html>
