<!DOCTYPE html> <!-- This file was generated by the script: -->

<html dir="ltr" lang="sr"> <!-- Ovaj HTML dokument je generisan od strane skripte -->
    <head> <!-- Head section contains metadata and links to resources -->
        <meta charset="utf-8"/> <!-- Specifies the character enco$g for the HTML document, ensuring proper display of Serbian characters -->
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/> <!-- Sets the viewport for responsive design, making the page look good on mobile devices -->
        <!-- This meta tag ensures the page scales correctly on different devices -->
        <meta content="Bane (NoOneNeo) Paunović" name="author"/> <!-- Metadata declaring the author of the page -->
        <!-- This meta tag specifies the author of the page, useful for SEO and attribution -->
        <meta content="Web Development, PHP, Loop"  name="keywords"/> <!-- Metadata for keywords, used by search engines for indexing -->
        <meta content="Web Development, Learning PHP Loop" name="description"/> <!-- Metadata for the page description, used by search engines and social media -->
        <meta content="index, follow" name="robots"/> <!-- Instructs search engine robots to index the page and follow its links -->
        <!-- This meta tag tells search engines to index the page and follow links -->
        <title>Learning PHP Loop</title> <!-- Sets the title of the webpage, shown in the browser tab and search results -->
        <!-- This title appears in the browser tab and search engine results -->
        <link href="/phpmysql/uvod/assets/css/main.css" rel="stylesheet"/> <!-- Links to the external CSS file for page styling -->
        <!-- This link connects the HTML document to the CSS file for styling -->
        <script defer="" src="/phpmysql/uvod/assets/js/main.js"></script>  <!-- Loads the JavaScript file after HTML is parsed; "defer" ensures it runs after DOM is ready -->
        <!-- This script tag loads the JavaScript file, ensuring it runs after the HTML is fully parsed -->
            <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">   Links to the Bootstrap CSS file -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>  Loads the Bootstrap JavaScript bundle, which includes Popper.js for tooltips and popovers -->
            <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">     Links to the Flatpickr CSS file for date and time picker -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>  Loads the Flatpickr JavaScript library for date and time picking functionality -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js" defer></script>  Loads the Pikaday JavaScript library for date picking functionality -->
            <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css"> Links to the Pikaday CSS file for styling the date picker -->
            <!-- <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">  Links to the jQuery UI CSS file for additional UI components and styles -->
            <!-- <script src="https://code.jquery.com/jquery-3.7.1.min.js" defer></script>  Loads the jQuery library, which is a dependency for many JavaScript libraries and plugins -->
            <!-- <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" defer></script> Loads the jQuery UI library, which provides additional UI components and interactions -->
        <link href="/phpmysql/uvod/assets/pic/Logo.png" rel="icon" type="image/x-icon"/> <!-- Sets the favicon icon shown in browser tabs -->
        <link href="/phpmysql/uvod/assets/pic/logo.png" rel="apple-touch-icon"/> <!-- Defines an icon for Apple devices when saving the page to the home screen -->
    </head> <!-- Body section contains the content of the webpage -->
    <!-- This is the main content area of the webpage -->
    <body> <!-- Start of body section -->
       
        <?php
            $ime = "Marko"; // deklariše promenljivu $ime i dodeljuje joj string "Marko"
            $godine = 19; // deklariše promenljivu $godine i dodeljuje joj integer 19
            $zanimanje = "programer"; // deklariše promenljivu $zanimanje i dodeljuje joj string "programer"

            // ako su svi uslovi tačni: ime je "Marko", godine preko 18 i zanimanje je "programer"
            if ($ime === "Marko" && $godine > 18 && $zanimanje === "programer" )
                echo "Marko je punoletni programer <br> <hr>" ; // ispisuje poruku da je Marko punoletni programer
            else 
                // u suprotnom koristi match izraz da utvrdi koji uslov nije ispunjen
                echo match (true) {
                    $ime !== "Marko"            => "Ne podudara se ime sa imenom <h3>$ime</h3> <br><hr>", // ako se ime ne slaže
                    $godine < 18                => "Osoba nije punoletna, ima samo <h3>$godine</h3> <br><hr>", // ako je maloletna
                    $zanimanje !== "programer"  => "Osoba nije programer po zanimanju, ona je <h3>$zanimanje</h3> <br><hr>", // ako zanimanje nije programer
                    default                     => "Ova osoba svakako nije programer", // ako nijedan od navedenih uslova
                };

            $broj = 4; // deklariše promenljivu $broj i dodeljuje joj integer 4

            // proverava da li je broj paran ili neparan
            if ($broj % 2 == 0) {
                echo "Broj je paran <br><hr>"; // ispisuje da je broj paran
            } else {
                echo "Broj je neparan <br> <hr>"; // ispisuje da je broj neparan
            }

            // petlja od 0 do 10 uključivo, koristi switch za različite prikaze po vrednosti $i
            for ($i = 0; $i <= 10; $i++) :
                switch ($i) :
                    case 0 : echo "🚐 <br> <hr>"; break; // ako je $i 0, prikaži ikonu kamiona
                    case 1 : echo "🧱 <br> <hr>"; break; // ako je $i 1, prikaži blok cigle
                    case 2 : echo "❤ <br> <hr>";  break; // ako je $i 2, prikaži srce
                    case 3 : echo "➡ <br> <hr>"; break;  // ako je $i 3, prikaži strelicu desno
                    case 4 : echo "❓ <br> <hr>"; break;  // ako je $i 4, prikaži upitnik
                    case 5 : echo "✔ <br> <hr>"; break;  // ako je $i 5, prikaži kvačicu
                    case 6 : echo "🧩 <br> <hr>"; break;  // ako je $i 6, prikaži slagalicu
                    case 7 : echo "👉 <br> <hr>"; break;  // ako je $i 7, prikaži prst koji pokazuje
                    case 8 : echo "🧰 <br> <hr>"; break;  // ako je $i 8, prikaži šrafciger i alat
                    case 9 : echo "🧭 <br> <hr>"; break; // ako je $i 9, prikaži kompas
                    case 10 : echo "🚗 <br> <hr>"; break; // ako je $i 10, prikaži automobil
                    default : echo "nepoznato <br> <hr>"; break; // za svaku drugu vrednost ispiši "nepoznato"
                endswitch;
            endfor;
            // nova petlja od 0 do 10, koristi match izraz za prekinuti kod posle $i === 8
            for ($i = 0; $i <= 10; $i++) :
                echo match($i) {
                    0 => " Malina <br> <hr>",      // ako je $i 0, prikaži "Malina"
                    1 => " Jagoda <br> <hr>",      // ako je $i 1, prikaži "Jagoda"
                    2 => " Kupina <br> <hr>",      // ako je $i 2, prikaži "Kupina"
                    3 => " Borovnica <br> <hr>",   // ako je $i 3, prikaži "Borovnica"
                    4 => " Sumsko voce <br> <hr>", // ako je $i 4, prikaži "Šumsko voće"
                    5 => " Tresnja <br> <hr>",     // ako je $i 5, prikaži "Trešnja"
                    6 => " Visnja <br> <hr>",      // ako je $i 6, prikaži "Višnja"
                    7 => " Borovnica <hr>",        // ako je $i 7, prikaži "Borovnica" sa horizontalom
                    8 => " Ribizla <hr>",          // ako je $i 8, prikaži "Ribizla" sa horizontalom
                    9 => " Kajsija <hr>",          // ako je $i 9, prikaži "Kajsija" sa horizontalom
                    default => "Banana",           // za sve ostale vrednosti prikaži "Banana"
                };
                if ($i === 8) break; // prekida petlju kada $i dostigne 8
            endfor;
        ?>
    </body>
</html>