<!DOCTYPE html> <!-- This file was generated by the script: -->

<html dir="ltr" lang="sr"> <!-- Ovaj HTML dokument je generisan od strane skripte -->
    <head> <!-- Head section contains metadata and links to resources -->
        <meta charset="utf-8"/> <!-- Specifies the character enco$g for the HTML document, ensuring proper display of Serbian characters -->
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/> <!-- Sets the viewport for responsive design, making the page look good on mobile devices -->
        <!-- This meta tag ensures the page scales correctly on different devices -->
        <meta content="Bane (NoOneNeo) Paunović" name="author"/> <!-- Metadata declaring the author of the page -->
        <!-- This meta tag specifies the author of the page, useful for SEO and attribution -->
        <meta content="Web Development, PHP, String"  name="keywords"/> <!-- Metadata for keywords, used by search engines for indexing -->
        <meta content="Web Development, Learning PHP String" name="description"/> <!-- Metadata for the page description, used by search engines and social media -->
        <meta content="index, follow" name="robots"/> <!-- Instructs search engine robots to index the page and follow its links -->
        <!-- This meta tag tells search engines to index the page and follow links -->
        <title>Learning PHP String</title> <!-- Sets the title of the webpage, shown in the browser tab and search results -->
        <!-- This title appears in the browser tab and search engine results -->
        <link href="/phpmysql/uvod/assets/css/main.css" rel="stylesheet"/> <!-- Links to the external CSS file for page styling -->
        <!-- This link connects the HTML document to the CSS file for styling -->
        <script defer="" src="/phpmysql/uvod/assets/js/main.js"></script>  <!-- Loads the JavaScript file after HTML is parsed; "defer" ensures it runs after DOM is ready -->
        <!-- This script tag loads the JavaScript file, ensuring it runs after the HTML is fully parsed -->
            <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">   Links to the Bootstrap CSS file -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>  Loads the Bootstrap JavaScript bundle, which includes Popper.js for tooltips and popovers -->
            <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">     Links to the Flatpickr CSS file for date and time picker -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>  Loads the Flatpickr JavaScript library for date and time picking functionality -->
            <!-- <script src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js" defer></script>  Loads the Pikaday JavaScript library for date picking functionality -->
            <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css"> Links to the Pikaday CSS file for styling the date picker -->
            <!-- <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">  Links to the jQuery UI CSS file for additional UI components and styles -->
            <!-- <script src="https://code.jquery.com/jquery-3.7.1.min.js" defer></script>  Loads the jQuery library, which is a dependency for many JavaScript libraries and plugins -->
            <!-- <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" defer></script> Loads the jQuery UI library, which provides additional UI components and interactions -->
        <link href="/phpmysql/uvod/assets/pic/Logo.png" rel="icon" type="image/x-icon"/> <!-- Sets the favicon icon shown in browser tabs -->
        <link href="/phpmysql/uvod/assets/pic/logo.png" rel="apple-touch-icon"/> <!-- Defines an icon for Apple devices when saving the page to the home screen -->
    </head> <!-- Body section contains the content of the webpage -->
    <!-- This is the main content area of the webpage -->
    <body> <!-- Start of body section -->
                    
            <?php
            // označava početak PHP koda

            // String sa kojim radimo
            $text = "Lorem ipsum dolorsit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";  
            // dodeljuje Lorem ipsum tekst promenljivoj $text

            $amet_pos = strpos($text, "amet");                                 // pronalazi indeks prve pojave reči "amet" u $text
            $sed_pos  = strpos($text, "sed");                                  // pronalazi indeks prve pojave reči "sed" u $text
            $end_pos  = $sed_pos - $amet_pos;                                  // izračunava koliko karaktera je između pozicija "amet" i "sed"

            echo "<br><hr>";                                                   // ispisuje HTML <br> i <hr> za razdvajanje u preglednom prikazu
            echo $amet_pos . "<br>";                                           // ispisuje poziciju reči "amet" i prelomi liniju
            echo $sed_pos;                                                     // ispisuje poziciju reči "sed"

            echo "<br><hr>";                                                   // ponovo razdvaja sekcije
            $preview = substr($text, $amet_pos, $end_pos);                     // uzima podniz iz $text počev od "amet" dužine $end_pos
            echo $preview . "... <br>";                                        // ispisuje izrezani tekst sa tri tačke i prelomom linije
            echo "<br><hr>";                                                   // dodaje još razdvajanja

            echo $text[1];                                                     // ispisuje drugi karakter originalnog teksta (indeks 1)
            echo "<h1> $text </h1>";                                           // prikazuje ceo tekst unutar velikog naslova

            // Prebrojimo broj karaktera
            $duzina = strlen($preview);                                        // računa dužinu niza $preview u karakterima
            echo "Ukupno karaktera: $preview <br><hr>";                       // greškom ispisuje sam $preview umesto broja dužine

            // For petlja koja prolazi kroz svaki karakter i ispisuje ga
            for ($a = 0; $a < $duzina; $a++) {                                 
                echo "Karakter na određenoj poziciji $a je : <strong>" 
                    . $text[$a] . "</strong>; <br>";                          // konkatenacijom ispisuje karakter na poziciji $a
            }

            echo "<br><hr>";                                                   // razdvaja sekciju

            $pozicija = strpos($text, "dolor");                                // pronalazi indeks prve pojave "dolor"
            echo $pozicija . "<br><hr>";                                       // ispisuje tu poziciju i razdvaja
            var_dump($pozicija);                                               // detaljno prikazuje tip i vrednost $pozicija
            echo "<br><hr>";                                                   // razdvaja nakon var_dump

            $preciscen_text = str_replace("dolor", "NoOneNeo", $text);         // zamenjuje sve pojave "dolor" sa "NoOneNeo"
            echo $preciscen_text . "<br><hr>";                                 // ispisuje izmenjeni tekst i razdvaja

            $mala_slova = strtolower($text);                                   // pretvara ceo tekst u mala slova
            echo $mala_slova . "<br><hr>";                                     // ispisuje i razdvaja

            $velika_slova = strtoupper($text);                                 // pretvara ceo tekst u velika slova
            echo $velika_slova . "<br><hr>";                                   // ispisuje i razdvaja

            $web_dev = "Danas ćemo da učimo PHP kako bi postali Full Stack Developer";  
            // tekst za proveru prisustva reči

            $rec = "učimo";                                                    // reč čije prisustvo proveravamo
            $sadrzi = str_contains($web_dev, $rec);                            // vraća true ako $web_dev sadrži "učimo"
            var_dump($sadrzi);                                                 // ispisuje tip i vrednost rezultata
            echo "<br><hr>";                                                   // razdvaja
            echo $sadrzi . "<br><hr>";                                         // ispisuje 1 ili prazno u zavisnosti od boolean vrednosti

            $start_rec   = strpos($web_dev, $rec);                             // pronalazi početnu poziciju reči u $web_dev
            $duzina_reci = strlen($rec);                                       // računa dužinu reči u karakterima
            echo "Broj karaktera u reci koju trazimo je : $duzina_reci, a njena startna pozicija je : $start_rec<br><hr>";
            // ispisuje dužinu reči i njenu poziciju

            // najbolji primer je da li je polje formatirano za mail 
            $email          = "branislav.paunovic@hotmail.com";                // test adresa
            $da_li_je_mail  = str_contains($email, "@");                       // proverava da li adresa sadrži "@"
            if ($da_li_je_mail) {
                echo "Ovo jeste ispravan format polja e-mail adrese<br><hr>";  // ako sadrži "@", tretira se kao validno
            } else {
                echo strtoupper("Ovo nije ispravan format polja e-mail adrese<br><hr>"); 
                // ako nedostaje "@", prikazuje poruku velikim slovima
            }           

            //$duzina_reci = strlen($web_dev, $rec);
            //echo "Broj karaktera u reci koju trazimo je : $duzina_reci, a njena startna pozicija je : $start_rec" . "<br><hr>";



            /* Funkcije 
            $amet_pos = strpos($text, "amet"); - // nalazi prvu poziciju podstringa "amet" u $text (int) ili false ako ga nema
            $preview = substr($text, $amet_pos, $end_pos); - // vraća deo $text počev od pozicije $amet_pos, u dužini $end_pos karaktera
            $duzina = strlen($preview); - // vraća dužinu stringa $preview (broj bajtova/karaktera za ASCII)
            $preciscen_text = str_replace("dolor", "NoOneNeo", $text); - // zamenjuje sva pojavljivanja "dolor" u $text sa "NoOneNeo" i vraća novi string
            $mala_slova = strtolower($text); - // pretvara sva slova u $text u mala (za UTF-8 bolje mb_strtolower)
            $velika_slova = strtoupper($text); - // pretvara sva slova u $text u velika (za UTF-8 bolje mb_strtoupper)
            */
            ?>
    </body>
</html>
